### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by Taylorminer** [openxrlab/xrprimer#17]
Thanks for your work! When I run "import xrprimer". It shows:
"from xrprimer_cpp.common import (
ImportError: liblapack.so.3: cannot open shared object file: No such file or directory
"
Can you help me ?

**Comment by yl-1993** [comment]
Hi @Taylorminer , thanks for checking out our codebase. We list it as a common issue in [FAQ](https://github.com/openxrlab/xrprimer/blob/main/docs/en/faq.md).

- If using conda, `conda install -c conda-forge lapack`
- If sudo is available, `apt update & apt -y install libatlas-base-dev`

**Comment by yl-1993** [comment]
Feel free to re-open this issue if something is not resolved
