### ISSUE TITLE
tbb_stddef cannot be read

### ISSUE THREAD

**Issue by wangni-bupt** [openxrlab/xrprimer#20]
ceres.cmake need change 

'''
commit | 941ea13475913ef8322584f7401633de9967ccc8
'''

more detail: https://groups.google.com/g/ceres-solver/c/2jwEdXX0d4o

**Comment by GACLove** [comment]
confirm,  see https://github.com/ceres-solver/ceres-solver/issues/669 , we will upgrade ceres.
