### ISSUE TITLE
无法打开 源 文件 "xrprimer_export.h"

### ISSUE THREAD

**Issue by sxlyiyiyi** [openxrlab/xrprimer#30]
新建一个c++项目，报错，无法打开 源 文件 "xrprimer_export.h" (dependency of "data_structure/camera/fisheye_camera.h")

**Comment by gappag** [comment]
xrprimer_export.h 来自哪里？ 是在cmake configure过程中生成的， 在install时候会copy到install 目录。
xrprimer的使用，可以参考这里：https://github.com/openxrlab/xrprimer/blob/main/cpp/samples/CMakeLists.txt
