### ISSUE TITLE
Could not find a package configuration file provided by "PnpSolver"

### ISSUE THREAD

**Issue by photoncanon** [openxrlab/xrprimer#31]
Hi I'm following the installation note step by step on Ubuntu 16.04. All the required dependencies are installed successfully. 
Then I start to  
`cmake -S . -Bbuild -DBUILD_EXTERNAL=ON -DCMAKE_BUILD_TYPE=Release
`

And it says

> CMake Error at cmake/dependencies.cmake:29 (find_package): Could not find a package configuration file provided by "PnpSolver" with any of the following names:

    PnpSolverConfig.cmake
    pnpsolver-config.cmake

> Add the installation prefix of "PnpSolver" to CMAKE_PREFIX_PATH or set  "PnpSolver_DIR" to a directory containing one of the above files.  If  "PnpSolver" provides a separate development package or SDK, be sure it has
  been installed. Call Stack (most recent call first):  CMakeLists.txt:90 (include)

I did not find any package named pnpsolver, does anyone know how to fix it?

Any help is appreciated.

**Comment by gappag** [comment]
Refer to the latest version, the link is here:  https://github.com/openxrlab/xrprimer/blob/main/docs/en/installation/cpp.md#compilation
