### ISSUE TITLE
多目相机标定异常

### ISSUE THREAD

**Issue by sxlyiyiyi** [openxrlab/xrprimer#33]
![image](https://user-images.githubusercontent.com/53137071/227149217-31a0f13c-2b6d-4045-853a-1a7ee6a3932d.png)
在进行多目鱼眼相机标定的时候，这里为什么不使用去畸变后的图像，MviewFisheyeCalibrator还是调用了MviewPinholeCalibrator

**Comment by LazyBusyYang** [comment]
Thank you for your feedback! Because the issue mentioned has been fixed in PR36, close this issue.
